'use client';
import {useRef,useState,useEffect,type PointerEvent} from 'react';
import {ChevronLeft,ChevronRight} from 'lucide-react';
import {Button} from './ui/button';
export default function DeckBoard({total,chosen=[],limit=1,onPick,ko=false,tint=''}:{total:number;chosen?:number[];limit?:number;onPick:(i:number)=>void;ko?:boolean;tint?:string}){
 const scroll=useRef<HTMLDivElement>(null);const drag=useRef({active:false,x:0,y:0,left:0,moved:false,mouse:false});const [edges,setEdges]=useState({left:false,right:false});
 const update=()=>{const el=scroll.current;if(el)setEdges({left:el.scrollLeft>2,right:el.scrollLeft+el.clientWidth<el.scrollWidth-2})};
 useEffect(()=>{const el=scroll.current;if(!el)return;const ro=new ResizeObserver(update);ro.observe(el);update();return()=>ro.disconnect()},[total]);
 function down(e:PointerEvent<HTMLDivElement>){if(e.pointerType==='mouse'&&e.button!==0)return;drag.current={active:true,x:e.clientX,y:e.clientY,left:scroll.current?.scrollLeft??0,moved:false,mouse:e.pointerType==='mouse'};}
 function move(e:PointerEvent<HTMLDivElement>){const d=drag.current;if(!d.active)return;const dx=e.clientX-d.x,dy=e.clientY-d.y;if(Math.hypot(dx,dy)>7)d.moved=true;if(d.mouse&&d.moved&&scroll.current){scroll.current.scrollLeft=d.left-dx;e.preventDefault();if(!e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.setPointerCapture(e.pointerId)}}
 function up(){drag.current.active=false}
 function shift(dir:number){const el=scroll.current;if(el)el.scrollBy({left:dir*el.clientWidth*.75,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})}
 return <div className="deck-board"><div className="deck-navigation"><Button variant="ghost" size="icon" aria-label={ko?'덱 왼쪽으로 이동':'Move deck left'} disabled={!edges.left} onClick={()=>shift(-1)}><ChevronLeft/></Button><p>{ko?'전체 덱에서 골라 주세요 · 좁은 화면에서는 좌우로 밀기':'Choose from the full deck · swipe or drag on narrow screens'}</p><Button variant="ghost" size="icon" aria-label={ko?'덱 오른쪽으로 이동':'Move deck right'} disabled={!edges.right} onClick={()=>shift(1)}><ChevronRight/></Button></div><div className="deck-scroll" ref={scroll} tabIndex={0} role="region" aria-label={ko?`${total}장 전체 덱 · 좌우 스크롤`:`Full ${total}-card deck, scroll left and right`} onScroll={update} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={()=>{drag.current.active=false;drag.current.moved=true}} onClickCapture={e=>{if(e.detail!==0&&drag.current.moved){e.preventDefault();e.stopPropagation();drag.current.moved=false}}}><div className={`full-deck ${total<78?'oracle-grid':''}`} style={{filter:tint||undefined}}>{Array.from({length:total},(_,i)=><button type="button" key={i} className={`deck-choice ${chosen.includes(i)?'selected':''}`} disabled={chosen.includes(i)||chosen.length>=limit} onClick={()=>onPick(i)} aria-pressed={chosen.includes(i)} aria-label={ko?`${i+1}번째 카드 선택`:`Select face-down card ${i+1}`}><img src="/card-back.webp" alt="" draggable={false}/>{chosen.includes(i)&&<span className="selection-order">{chosen.indexOf(i)+1}</span>}</button>)}</div></div></div>
}
