'use client';
import {useState,useRef,useEffect,type CSSProperties} from 'react';
import {Moon,Shuffle,ArrowRight,Heart,RotateCcw,Sparkles,BookOpen} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {cards,questions,makeDeck,shuffled,meaning,positionMeaning,synthesis,clarifiers,messages,type Draw} from '@/lib/tarot';
import {Header,Footer} from '@/components/site-shell';
type Stage='ready'|'shuffling'|'pick'|'reveal'|'clarify-ready'|'clarify-pick'|'clarify-reveal'|'message-ready'|'message-pick'|'message-reveal'|'result';
export default function ReadingRoom({initialQuestion='their-feelings'}:{initialQuestion?:string}){
 const q=questions.find(x=>x.id===initialQuestion)??questions[0];
 const [stage,setStage]=useState<Stage>('ready');const [deck,setDeck]=useState<Draw[]>([]);const [chosen,setChosen]=useState<number[]>([]);const [flipped,setFlipped]=useState<number[]>([]);const [oracleDeck,setOracleDeck]=useState<number[]>([]);const [oracle,setOracle]=useState<number|null>(null);const [messageDeck,setMessageDeck]=useState<number[]>([]);const [message,setMessage]=useState<number|null>(null);const [page,setPage]=useState(0);const timer=useRef<ReturnType<typeof setTimeout>|null>(null);const lock=useRef(false);const resultRef=useRef<HTMLDivElement>(null);
 useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current)},[]);
 useEffect(()=>{if(stage==='result')resultRef.current?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'})},[stage]);
 const drawn=chosen.map(i=>deck[i]);const count=q.count;const isOracle=stage.startsWith('clarify');const isMessage=stage.startsWith('message');const allFlipped=flipped.length===count;
 function reset(){if(timer.current)clearTimeout(timer.current);lock.current=false;setStage('ready');setDeck([]);setChosen([]);setFlipped([]);setOracle(null);setMessage(null);setPage(0)}
 function shuffle(){if(lock.current)return;lock.current=true;setDeck(makeDeck());setChosen([]);setFlipped([]);setPage(0);setStage('shuffling');timer.current=setTimeout(()=>{setStage('pick');lock.current=false},900)}
 function pick(i:number){if(stage!=='pick'||lock.current||chosen.includes(i)||chosen.length>=count)return;const next=[...chosen,i];setChosen(next);if(next.length===count){lock.current=true;timer.current=setTimeout(()=>{setStage('reveal');lock.current=false},350)}}
 function flip(i:number){if(stage!=='reveal')return;setFlipped(old=>old.includes(i)?old:[...old,i])}
 function beginOracle(){setOracleDeck(shuffled(clarifiers.map((_,i)=>i)));setStage('clarify-pick')}
 function beginMessage(){setMessageDeck(shuffled(messages.map((_,i)=>i)));setStage('message-pick')}
 const frontTitle=isOracle?'The Clarity Deck':isMessage?'The Message Deck':'The Classic Tarot';
 const title=stage==='ready'?(q.id==='daily'||q.id==='three-card'||q.id==='yes-no'?'Take a breath. Hold your question.':'Take a breath. Think of them.'):stage==='shuffling'?'A little space for your question…':stage==='pick'?`Choose ${count===1?'one card':`${count} cards`}. Trust your first pull.`:stage==='reveal'?'Turn over your cards.':stage==='clarify-ready'?'Look a little closer.':stage==='clarify-pick'?'Choose one card for clarity.':stage==='clarify-reveal'?'A little more perspective.':stage==='message-ready'?'One last card, just for you.':stage==='message-pick'?'Choose your closing message.':stage==='message-reveal'?'A thought to take with you.':'Your cards are on the table.';
 const hint=stage==='ready'?'Your question can stay in your mind.':stage==='pick'?`${chosen.length} of ${count} selected · ${page*15+1}–${Math.min(page*15+15,78)} of 78 cards`:stage==='reveal'?'Tap each card to reveal it.':isOracle?'A different deck. A practical point to reflect on.':isMessage?'A message for you, not a claim about their thoughts.':stage==='result'?'Keep what helps you reflect. Leave what does not.':'Let the rest of the day wait for a moment.';
 const showMainFan=['ready','shuffling','pick'].includes(stage);const showSpread=['reveal','result'].includes(stage);const showSmallFan=['clarify-ready','clarify-pick','message-ready','message-pick'].includes(stage);
 return <><Header/><main className="room"><div className="room-heading"><span className="eyebrow">A quiet moment for matters of the heart</span><h1>{q.title}</h1><p>Shuffle the deck. Choose your cards. Find a little perspective.</p></div><div className="question-list" aria-label="Choose a reading">{questions.slice(0,6).map(item=><a key={item.id} className="question-pill" aria-current={q.id===item.id?"page":undefined} href={item.id==='their-feelings'?'/':`/reading/${item.id}`}>{item.label}</a>)}</div><div className="step-line" aria-label="Reading progress"><span className={!isOracle&&!isMessage&&stage!=='result'?'current':''}>01 &nbsp; YOUR CARDS</span><span className={isOracle?'current':''}>02 &nbsp; CLARITY</span><span className={isMessage?'current':''}>03 &nbsp; A MESSAGE</span></div><section className="table" aria-label="Tarot reading table"><div className="table-top"><span>{frontTitle}</span><Moon size={18}/><span>{isOracle?'12 cards':isMessage?'30 cards':'78 cards · full deck'}</span></div><h2>{title}</h2><p className="hint" aria-live="polite">{hint}</p>
 {showMainFan&&<div className={`fan ${stage==='ready'?'stacked':''} ${stage==='shuffling'?'shuffling':''}`} aria-label="Face-down tarot cards">{Array.from({length:stage==='pick'?Math.min(15,78-page*15):15},(_,i)=>{const idx=page*15+i;return <button type="button" key={`${page}-${i}`} className={`pick-card ${chosen.includes(idx)?'picked':''}`} style={{'--i':i-(stage==='pick'?Math.min(15,78-page*15)-1:14)/2,'--y':Math.abs(i-(stage==='pick'?Math.min(15,78-page*15)-1:14)/2)**2*.6,zIndex:i} as CSSProperties} onClick={()=>pick(idx)} disabled={stage!=='pick'||chosen.includes(idx)} aria-label={`Select face-down card ${idx+1}`}><img src="/card-back.webp" alt="" draggable={false}/></button>})}</div>}
 {showSpread&&<div className="spread">{drawn.map((d,i)=><div className="spread-slot" key={d.card.id}><button type="button" onClick={()=>flip(i)} disabled={stage==='result'||flipped.includes(i)} aria-label={flipped.includes(i)||stage==='result'?`${d.card.name}, ${d.reversed?'reversed':'upright'}`:`Reveal card ${i+1}`} className={`reveal-card ${flipped.includes(i)||stage==='result'?'revealed':''}`}><div className="flip-inner"><div className="card-back"><img src="/card-back.webp" alt=""/></div><div className="card-front" aria-hidden={!flipped.includes(i)&&stage!=='result'}><img src={d.card.image} alt={d.card.name} style={{transform:d.reversed?'rotate(180deg)':undefined}}/><span className="card-name">{d.card.name}</span><span className="orientation">{d.reversed?'Reversed':'Upright'}</span></div></div></button><p>{q.positions[i]}</p></div>)}</div>}
 {showSmallFan&&<div className={`fan ${stage.endsWith('ready')?'stacked':''}`} aria-label={isOracle?'Clarity cards':'Message cards'}>{Array.from({length:9},(_,i)=><button type="button" key={i} className="pick-card" style={{'--i':i-4,'--y':Math.abs(i-4)**2,zIndex:i,filter:isOracle?'hue-rotate(290deg) saturate(.65)':'hue-rotate(30deg)'} as CSSProperties} disabled={stage.endsWith('ready')} onClick={()=>{if(isOracle){setOracle(oracleDeck[i]);setStage('clarify-reveal')}else{setMessage(messageDeck[i]);setStage('message-reveal')}}} aria-label={`Pick ${isOracle?'clarity':'message'} card ${i+1}`}><img src="/card-back.webp" alt=""/></button>)}</div>}
 {stage==='clarify-reveal'&&oracle!==null&&<div className="oracle-reveal"><Sparkles size={26}/><h3>{clarifiers[oracle][0]}</h3><p>{clarifiers[oracle][1]}</p></div>}
 {stage==='message-reveal'&&message!==null&&<div className="oracle-reveal"><Heart size={26}/><p className="message-text">“{messages[message]}”</p></div>}
 <div className="actions">{stage==='ready'&&<Button className="primary-btn" onClick={shuffle}><Shuffle/>Shuffle the deck</Button>}{stage==='shuffling'&&<Button className="primary-btn" disabled>Shuffling…</Button>}{stage==='pick'&&<><Button className="secondary-btn" onClick={()=>setPage(p=>(p+1)%6)}>More cards</Button>{chosen.length===0&&<Button className="secondary-btn" onClick={shuffle}><Shuffle/>Shuffle again</Button>}</>}{stage==='reveal'&&<Button className="primary-btn" disabled={!allFlipped} onClick={()=>setStage('clarify-ready')}>{allFlipped?'Draw a clarifier':`Reveal ${count-flipped.length} more ${count-flipped.length===1?'card':'cards'}`}<ArrowRight/></Button>}{stage==='clarify-ready'&&<Button className="primary-btn" onClick={beginOracle}><Shuffle/>Shuffle the Clarity Deck</Button>}{stage==='clarify-reveal'&&<Button className="primary-btn" onClick={()=>setStage('message-ready')}>One final message<ArrowRight/></Button>}{stage==='message-ready'&&<Button className="primary-btn" onClick={beginMessage}><Shuffle/>Shuffle the Message Deck</Button>}{stage==='message-reveal'&&<Button className="primary-btn" onClick={()=>setStage('result')}>Read the whole story<ArrowRight/></Button>}{stage==='result'&&<Button className="secondary-btn" onClick={reset}><RotateCcw/>Begin a new reading</Button>}</div></section><div className="under-table"><p><Heart size={14}/>Free readings. No sign-up. Just a moment for you.</p><p><Moon size={14}/>For reflection, not certainty.</p></div>
 {stage==='result'&&<div className="result" ref={resultRef} tabIndex={-1}><div className="result-header"><span className="eyebrow">Your love reading</span><h2>{q.title}</h2><p>Different cards. One conversation with yourself.</p></div>{q.id==='yes-no'&&<div className="synthesis"><span className="eyebrow">Symbolic lean</span><h3>{(drawn[0].reversed?-drawn[0].card.tone:drawn[0].card.tone)>0?'Leaning yes — with intention':(drawn[0].reversed?-drawn[0].card.tone:drawn[0].card.tone)<0?'Leaning no — protect your energy':'Not clear yet — seek more information'}</h3><p>A symbolic prompt, not a factual prediction or a decision made for you.</p></div>}{drawn.map((d,i)=><article className="reading-item" key={d.card.id}><span className="index">0{i+1}</span><div><span className="eyebrow">{q.positions[i]} · {d.reversed?'Reversed':'Upright'}</span><h3>{d.card.name}</h3><p>{positionMeaning(d,q,i)}</p><a className="learn-link" href={`/card-meanings/${d.card.slug}`}>Explore this card <ArrowRight size={13}/></a></div></article>)}<div className="synthesis"><span className="eyebrow">The cards together</span><h3>{drawn.length===1?drawn[0].card.keyword:'The thread through your reading'}</h3><p>{drawn.length===1?`${meaning(drawn[0])} ${q.focus}`:synthesis(drawn,q)}</p>{oracle!==null&&<p><strong>Your clarifier — {clarifiers[oracle][0]}.</strong> {clarifiers[oracle][1]}</p>}<p><strong>One grounded next step.</strong> {q.prompt}</p></div>{message!==null&&<div className="closing"><span className="eyebrow">A message for you</span><p>“{messages[message]}”</p></div>}<div className="actions"><Button className="secondary-btn" onClick={reset}><RotateCcw/>Start again</Button><a className="learn-link" href="/card-meanings"><BookOpen size={16}/>Explore the card meanings</a></div><p className="result-note">These randomly drawn cards offer symbolic reflection. They cannot reveal another person’s private thoughts or guarantee what will happen. Give real conversations and your own boundaries the final word.</p></div>}
 <section className="other-readings"><a href="/reading/daily"><Moon size={18}/><div><span className="eyebrow">A moment for yourself</span><h3>Today’s tarot</h3></div><ArrowRight size={17}/></a><a href="/fortune-cookie"><Sparkles size={18}/><div><span className="eyebrow">Something light</span><h3>Your fortune cookie</h3></div><ArrowRight size={17}/></a><a href="/reading/three-card"><BookOpen size={18}/><div><span className="eyebrow">See the bigger picture</span><h3>A three-card reading</h3></div><ArrowRight size={17}/></a></section></main><Footer/></>
}
