'use client';
import {useState,useRef,useEffect,type CSSProperties} from 'react';
import {Shuffle,ArrowRight,RotateCcw,Sparkles,BookOpen} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {cards,questions,makeDeck,shuffled,meaning,positionMeaning,synthesis,clarifiers,messages,type Draw} from '@/lib/tarot';
import CardDetails from '@/components/card-details';
import {getScenario,scenarioList,situations,detailedReading,matchingMessage,spreadConnection} from '@/lib/reading-scenarios';
import DeckBoard from '@/components/deck-board';
import {koCards,koQuestions,koClarifiers,koMessages,koPosition,koSynthesis} from '@/lib/tarot-ko';
import {Header,Footer} from '@/components/site-shell';
type Stage='ready'|'shuffling'|'pick'|'reveal'|'clarify-ready'|'clarify-shuffling'|'clarify-pick'|'clarify-reveal'|'message-ready'|'message-shuffling'|'message-pick'|'message-reveal'|'result';
export default function ReadingRoom({initialQuestion='their-feelings',initialKo=false}:{initialQuestion?:string;initialKo?:boolean}){
 const [ko,setKo]=useState(initialKo);const t=(en:string,kr:string)=>ko?kr:en;const link=(p:string)=>p+(ko?'?lang=ko':'');
 const [questionId,setQuestionId]=useState(initialQuestion); const q=getScenario(questionId,false); const [situation,setSituation]=useState(q.situation==='general'?'breakup':q.situation);
 const kq=getScenario(questionId,true);const shownQ=ko?kq:q;const oracleTexts=ko?koClarifiers:clarifiers;const messageTexts=ko?koMessages:messages;
 useEffect(()=>{document.documentElement.lang=ko?'ko':'en'},[ko]);
 const [stage,setStage]=useState<Stage>('ready');const [deck,setDeck]=useState<Draw[]>([]);const [chosen,setChosen]=useState<number[]>([]);const [flipped,setFlipped]=useState<number[]>([]);const [oracleDeck,setOracleDeck]=useState<number[]>([]);const [oracle,setOracle]=useState<number|null>(null);const [messageDeck,setMessageDeck]=useState<number[]>([]);const [message,setMessage]=useState<number|null>(null);const timer=useRef<ReturnType<typeof setTimeout>|null>(null);const lock=useRef(false);const resultRef=useRef<HTMLDivElement>(null);
 useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current)},[]);
 useEffect(()=>{if(stage==='result')resultRef.current?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'})},[stage]);
 const drawn=chosen.map(i=>({...deck[i],card:ko?koCards[deck[i].card.id]:deck[i].card}));const count=q.count;const isOracle=stage.startsWith('clarify');const isMessage=stage.startsWith('message');const allFlipped=flipped.length===count;
 function reset(){if(timer.current)clearTimeout(timer.current);lock.current=false;setStage('ready');setDeck([]);setChosen([]);setFlipped([]);setOracle(null);setMessage(null)}
 function shuffle(){if(lock.current)return;lock.current=true;setDeck(makeDeck());setChosen([]);setFlipped([]);setStage('shuffling');timer.current=setTimeout(()=>{setStage('pick');lock.current=false},900)}
 function pick(i:number){if(stage!=='pick'||lock.current||chosen.includes(i)||chosen.length>=count)return;const next=[...chosen,i];setChosen(next);if(next.length===count){lock.current=true;timer.current=setTimeout(()=>{setStage('reveal');lock.current=false},350)}}
 function flip(i:number){if(stage!=='reveal')return;setFlipped(old=>old.includes(i)?old:[...old,i])}
 function beginOracle(){if(lock.current)return;lock.current=true;setOracleDeck(shuffled(clarifiers.map((_,i)=>i)));setStage('clarify-shuffling');timer.current=setTimeout(()=>{setStage('clarify-pick');lock.current=false},900)}
 function beginMessage(){if(lock.current)return;lock.current=true;setMessageDeck(shuffled(messages.map((_,i)=>i)));setStage('message-shuffling');timer.current=setTimeout(()=>{setStage('message-pick');lock.current=false},900)}
 const frontTitle=isOracle?t('The Clarity Deck','조언 카드'):isMessage?t('The Message Deck','메시지 덱'):t('The Classic Tarot','클래식 타로');
 const title=stage.endsWith('shuffling')?'Shuffling your deck…':stage==='ready'?(q.id==='daily'||q.id==='three-card'||q.id==='yes-no'?'Take a breath. Hold your question.':'Take a breath. Think of them.'):stage==='shuffling'?'A little space for your question…':stage==='pick'?`Choose ${count===1?'one card':`${count} cards`}. Trust your first pull.`:stage==='reveal'?'Turn over your cards.':stage==='clarify-ready'?'Look a little closer.':stage==='clarify-pick'?'Choose one card for clarity.':stage==='clarify-reveal'?'A little more perspective.':stage==='message-ready'?'One last card, just for you.':stage==='message-pick'?'Choose your closing message.':stage==='message-reveal'?'A thought to take with you.':'Your cards are on the table.';
 const hint=stage==='ready'?'Your question can stay in your mind.':stage==='pick'?`${chosen.length} of ${count} selected · all 78 cards on the table`:stage==='reveal'?'Tap each card to reveal it.':isOracle?'A different deck. A practical point to reflect on.':isMessage?'A message for you, not a claim about their thoughts.':stage==='result'?'Keep what helps you reflect. Leave what does not.':'Let the rest of the day wait for a moment.';
 const koreanTitles:Record<Stage,string>={ready:'궁금한 질문을 골랐다면 시작해요.',shuffling:'카드를 섞고 있어요…',pick:`마음이 가는 카드 ${count}장을 골라 주세요.`,reveal:'고른 카드를 뒤집어 보세요.', 'clarify-ready':'지금 필요한 조언을 만나볼까요?', 'clarify-shuffling':'조언 카드를 섞고 있어요…', 'clarify-pick':'조언 카드 한 장을 골라 주세요.', 'clarify-reveal':'지금 필요한 조언', 'message-ready':'마지막 한 장은 나를 위해.', 'message-shuffling':'메시지 카드를 섞고 있어요…', 'message-pick':'마무리 메시지를 골라 주세요.', 'message-reveal':'마음에 새겨둘 한마디',result:'모든 카드가 모였어요.'};
 const koreanHint=stage==='pick'?`${count}장 중 ${chosen.length}장 선택 · 78장 전체 덱`:stage==='reveal'?'카드를 한 장씩 눌러 확인하세요.':stage==='ready'?'질문은 마음속으로만 생각해도 괜찮아요.':isOracle?'타로 해석과 함께 참고할 조언 한 장을 뽑아요.':isMessage?'상대의 속마음을 대신하는 말이 아닌, 나를 위한 메시지예요.':stage==='result'?'선택한 질문에 맞춰 카드별 해석을 확인하세요.':'잠시 다른 생각은 내려놓아도 좋아요.';
 const showMainFan=['ready','shuffling','pick'].includes(stage);const showSpread=['reveal','result'].includes(stage);const showSmallFan=['clarify-ready','clarify-shuffling','clarify-pick','message-ready','message-shuffling','message-pick'].includes(stage);
 return <><Header ko={ko} onLanguage={value=>{setKo(value);const url=new URL(window.location.href);url.searchParams.set("lang",value?"ko":"en");window.history.replaceState(null,"",url)}}/><main className="room" lang={ko?"ko":"en"}><div className="room-heading"><span className="eyebrow">{t('A quiet moment for matters of the heart','연애 · 썸 · 재회 고민')}</span><h1>{shownQ.title}</h1><p>{t('Shuffle the deck. Choose your cards. Find a little perspective.','아래에서 내 상황과 궁금한 질문을 고르면, 뽑은 카드로 해석해 드려요.')}</p></div><div className="situation-list" aria-label={t('Your situation','나의 상황')}>{situations.map(item=><button key={item.id} disabled={stage!=='ready'} aria-pressed={situation===item.id} onClick={()=>{setSituation(item.id);setQuestionId(scenarioList(false).find(q=>q.situation===item.id)!.id)}}>{ko?item.ko:item.en}</button>)}</div><div className="question-list" aria-label={t('Choose your question','질문 선택')}>{scenarioList(ko).filter(item=>item.situation===situation).map(item=><button key={item.id} disabled={stage!=='ready'} className="question-pill" aria-current={q.id===item.id?"page":undefined} onClick={()=>setQuestionId(item.id)}>{item.label}</button>)}</div><div className="reading-options">{stage==='ready'?<button className="learn-link" onClick={()=>setQuestionId('yes-no')}>{t('A quick Yes / No question','간단한 예 / 아니오 질문')}</button>:<button className="learn-link" onClick={reset}>{t('Restart and choose a question','처음으로 돌아가 질문 다시 선택')}</button>}</div><p className="deck-intro">{t(`Three decks, ${count+2} cards: ${count} tarot cards, one advice card and one closing message.`,`타로 ${count}장으로 질문을 풀어보고, 조언 1장과 메시지 1장을 더 뽑아요. 총 ${count+2}장이에요.`)}</p>{q.id==='three-card'&&<p className="deck-intro">{t('Card 1: Past · Card 2: Present · Card 3: Possible future. This is not a month-by-month forecast.','1번 과거 · 2번 현재 · 3번 미래의 흐름 — 월별 예측이 아닌, 한 질문의 시간 흐름을 읽어요.')}</p>}<div className="step-line" aria-label="Reading progress"><span className={!isOracle&&!isMessage&&stage!=='result'?'current':''}>01 &nbsp; {t('YOUR CARDS','타로 카드')}</span><span className={isOracle?'current':''}>02 &nbsp; {t('CLARITY','조언 카드')}</span><span className={isMessage?'current':''}>03 &nbsp; {t('A MESSAGE','마지막 메시지')}</span></div><section className="reading-table" aria-label="Tarot reading table"><div className="reading-table-top"><span>{frontTitle}</span><Sparkles size={18}/><span>{isOracle?t('12 cards','12장'):isMessage?t('30 cards','30장'):t('78 cards · full deck','78장 · 전체 덱')}</span></div><h2>{ko?koreanTitles[stage]:title}</h2><p className="hint" aria-live="polite">{ko?koreanHint:hint}</p>
 {stage==='pick'?<DeckBoard total={deck.length} chosen={chosen} limit={count} onPick={pick} ko={ko}/>:showMainFan&&<div className={`fan stacked ${stage==='shuffling'?'shuffling':''}`} aria-label="Shuffled tarot deck">{Array.from({length:15},(_,i)=><div key={i} className="pick-card" style={{'--i':i-7,'--y':0,zIndex:i} as CSSProperties}><img src="/card-back.webp" alt="" draggable={false}/></div>)}</div>}

 {showSpread&&<div className="spread">{drawn.map((d,i)=><div className="spread-slot" key={d.card.id}><button type="button" onClick={()=>flip(i)} disabled={stage==='result'||flipped.includes(i)} aria-label={flipped.includes(i)||stage==='result'?`${d.card.name}, ${d.reversed?t('reversed','역방향'):t('upright','정방향')}`:t(`Reveal card ${i+1}`,`${i+1}번째 카드 뒤집기`)} className={`reveal-card ${flipped.includes(i)||stage==='result'?'revealed':''}`}><div className="flip-inner"><div className="card-back"><img src="/card-back.webp" alt=""/></div><div className="card-front" aria-hidden={!flipped.includes(i)&&stage!=='result'}><img src={d.card.image} alt={d.card.name} style={{transform:d.reversed?'rotate(180deg)':undefined}}/><span className="card-name">{d.card.name}</span><span className="orientation">{d.reversed?t('Reversed','역방향'):t('Upright','정방향')}</span></div></div></button><p>{shownQ.positions[i]}</p></div>)}</div>}
 {showSmallFan&&((stage.endsWith('ready')||stage.endsWith('shuffling'))?<div className={`fan stacked ${stage.endsWith('shuffling')?'shuffling':''}`}>{Array.from({length:12},(_,i)=><div key={i} className="pick-card" style={{'--i':i-6,'--y':0,filter:isOracle?'hue-rotate(290deg) saturate(.65)':'hue-rotate(30deg)'} as CSSProperties}><img src="/card-back.webp" alt=""/></div>)}</div>:<DeckBoard key={isOracle?'clarity':'message'} total={isOracle?oracleDeck.length:messageDeck.length} ko={ko} tint={isOracle?'hue-rotate(290deg) saturate(.65)':'hue-rotate(30deg)'} onPick={i=>{if(isOracle){setOracle(oracleDeck[i]);setStage('clarify-reveal')}else{setMessage(messageDeck[i]);setStage('message-reveal')}}}/>)}
 {stage==='clarify-reveal'&&oracle!==null&&<div className="oracle-reveal"><Sparkles size={26}/><h3>{oracleTexts[oracle][0]}</h3><p>{oracleTexts[oracle][1]}</p></div>}
 {stage==='message-reveal'&&message!==null&&<div className="oracle-reveal"><Sparkles size={26}/><p className="message-text">“{matchingMessage(message,shownQ,ko,messageTexts[message])}”</p></div>}
 <div className="actions">{(stage==='clarify-pick'||stage==='message-pick')&&<Button className="secondary-btn" onClick={isOracle?beginOracle:beginMessage}><Shuffle/>{t('Shuffle again','다시 섞기')}</Button>}{(stage==='clarify-shuffling'||stage==='message-shuffling')&&<Button disabled className="primary-btn">{t('Shuffling…','섞는 중…')}</Button>}{stage==='ready' &&<Button className="primary-btn" onClick={shuffle}><Shuffle/>{t('Shuffle the deck','카드 섞기')}</Button>}{stage==='shuffling'&&<Button className="primary-btn" disabled>{t('Shuffling…','섞는 중…')}</Button>}{stage==='pick'&&<>{chosen.length===0&&<Button className="secondary-btn" onClick={shuffle}><Shuffle/>{t('Shuffle again','다시 섞기')}</Button>}</>}{stage==='reveal'&&<Button className="primary-btn" disabled={!allFlipped} onClick={()=>setStage('clarify-ready')}>{allFlipped?t('Draw a clarifier','조언 카드 뽑기'):ko?`${count-flipped.length}장을 더 뒤집어 주세요`:`Reveal ${count-flipped.length} more cards`}<ArrowRight/></Button>}{stage==='clarify-ready'&&<Button className="primary-btn" onClick={beginOracle}><Shuffle/>{t('Shuffle the Clarity Deck','조언 카드 섞기')}</Button>}{stage==='clarify-reveal'&&<Button className="primary-btn" onClick={()=>setStage('message-ready')}>{t('One final message','마지막 메시지 뽑기')}<ArrowRight/></Button>}{stage==='message-ready'&&<Button className="primary-btn" onClick={beginMessage}><Shuffle/>{t('Shuffle the Message Deck','메시지 덱 섞기')}</Button>}{stage==='message-reveal'&&<Button className="primary-btn" onClick={()=>setStage('result')}>{t('Read the whole story','전체 해석 보기')}<ArrowRight/></Button>}{stage==='result'&&<Button className="secondary-btn" onClick={reset}><RotateCcw/>{t('Begin a new reading','새 리딩 시작')}</Button>}</div></section><div className="under-table"><p><Sparkles size={14}/>{t('When thoughts crowd in, listen to the cards.','카드마다 선택한 질문에 맞는 해석을 읽을 수 있어요.')}</p><p><Sparkles size={14}/>{t('Messages across past, present and possible futures.','상대의 실제 마음과 결정은 대화로 확인하세요.')}</p></div>
 {stage==='result'&&<div className="result" ref={resultRef} tabIndex={-1}><div className="result-header"><span className="eyebrow">{t('Your love reading','나의 연애 타로')}</span><h2>{shownQ.title}</h2><p>{t('Different cards. One conversation with yourself.','뽑은 카드가 뜻하는 것과 지금 해볼 일을 정리했어요.')}</p><p>{shownQ.focus}</p></div>{q.id==='yes-no'&&<div className="synthesis"><span className="eyebrow">{t('Symbolic lean','카드가 제안하는 방향')}</span><h3>{(drawn[0].reversed?-drawn[0].card.tone:drawn[0].card.tone)>0?t('Leaning yes — with intention','예에 가까워요 — 필요한 조건도 확인하세요'):(drawn[0].reversed?-drawn[0].card.tone:drawn[0].card.tone)<0?t('Leaning no — protect your energy','아니오에 가까워요 — 내 마음을 지켜 주세요'):t('Not clear yet — seek more information','아직 불분명해요 — 더 확인해 보세요')}</h3><p>{t('A symbolic prompt, not a factual prediction or a decision made for you.','확정된 예언이나 결정을 대신하는 답이 아닌, 생각을 돕는 상징이에요.')}</p></div>}{drawn.map((d,i)=><article className="reading-item" key={d.card.id}><span className="index">0{i+1}</span><div><span className="eyebrow">{shownQ.positions[i]} · {d.reversed?t('Reversed','역방향'):t('Upright','정방향')}</span><h3>{d.card.name}</h3>{detailedReading(d,shownQ,i,ko).map(part=><section className="interpretation-part" key={part.title}><h4>{part.title}</h4><p>{part.text}</p></section>)}<CardDetails card={d.card} ko={ko}>{t('Explore this card','이 카드의 의미 보기')}</CardDetails></div></article>)}<div className="synthesis"><span className="eyebrow">{t('The cards together','카드를 함께 읽으면')}</span><h3>{drawn.length===1?drawn[0].card.keyword:t('The thread through your reading','이번 해석의 핵심')}</h3><p>{drawn.length===1?`${meaning(drawn[0])} ${shownQ.focus}`:ko?koSynthesis(drawn,shownQ):shownQ.focus}</p><p>{spreadConnection(drawn,shownQ,ko)}</p>{oracle!==null&&<p><strong>{t("Your clarifier — ","조언 카드 — ")}{oracleTexts[oracle][0]}.</strong> {oracleTexts[oracle][1]}</p>}<p><strong>{t('One grounded next step.','지금 해볼 일.')}</strong> {shownQ.prompt}</p></div>{message!==null&&<div className="closing"><span className="eyebrow">{t('A message for you','나를 위한 메시지')}</span><p>“{matchingMessage(message,shownQ,ko,messageTexts[message])}”</p></div>}<div className="actions"><Button className="secondary-btn" onClick={reset}><RotateCcw/>{t('Start again','다시 시작')}</Button></div><p className="result-note">{t('These randomly drawn cards offer symbolic reflection. They cannot reveal another person’s private thoughts or guarantee what will happen. Give real conversations and your own boundaries the final word.','무작위로 뽑은 카드로 상황과 마음을 돌아보는 리딩이에요. 타인의 실제 속마음이나 미래를 확정하지는 않아요. 실제 대화와 행동, 나의 기준을 함께 살펴보세요.')}</p></div>}
 <section className="other-readings"><a href={link("/reading/daily")}><Sparkles size={18}/><div><span className="eyebrow">{t('A moment for yourself','타로 1장 · 오늘 참고할 조언')}</span><h3>{t('Today’s tarot','오늘은 무엇을 신경 쓰면 좋을까?')}</h3></div></a><a href={link("/fortune-cookie")}><Sparkles size={18}/><div><span className="eyebrow">{t('Something light','가볍게 열어 보기')}</span><h3>{t('Your fortune cookie','나의 포춘쿠키')}</h3></div></a><a href={link("/reading/three-card")}><BookOpen size={18}/><div><span className="eyebrow">{t('Where are we now?','타로 3장 · 과거, 현재, 앞으로의 관계')}</span><h3>{t('Past · Present · Future','이 관계는 앞으로 어떻게 될까?')}</h3></div></a></section></main><Footer ko={ko}/></>
}
