export type Card = {id:number;slug:string;name:string;suit:string;keyword:string;upright:string;reversed:string;tone:number;image:string};
// Original editorial interpretations. No AI API calls or personal information required.
const majors:[string,string,string,string,number][] = [
['The Fool','A fresh start','Curiosity opens a door, but a new spark still needs time to become trust.','Excitement can outrun good judgment. Slow down before making a promise.',1],
['The Magician','Intentional action','There is room to turn attraction into a clear gesture. Words matter when actions support them.','Charm without follow-through can confuse the picture. Look for consistency.',1],
['The High Priestess','Unspoken feelings','Something is still private or unformed. Give uncertainty space without filling it with assumptions.','Guessing may be drowning out what you already know. Separate intuition from wishful thinking.',0],
['The Empress','Warmth and care','Affection grows through comfort, attention and everyday kindness. Notice where care is freely shared.','Overgiving can leave you depleted. Nurturing a connection should not require neglecting yourself.',1],
['The Emperor','Steady boundaries','Clear intentions and dependable behavior create safety. Structure can support a lasting connection.','Control or rigidity may be limiting closeness. A healthy boundary leaves both people a voice.',0],
['The Hierophant','Shared values','Commitment becomes more possible when expectations and values align. Discuss what a relationship means to each of you.','An inherited rule may not fit this connection. Make room for an honest definition of commitment.',0],
['The Lovers','Mutual choice','Attraction invites a meaningful choice. Shared values and willing participation matter as much as chemistry.','Desire and values may be pulling in different directions. Connection needs a choice from both sides.',1],
['The Chariot','Forward movement','Momentum comes from choosing a direction and acting with purpose. Pursuit works best when it respects consent.','Pushing for progress may create resistance. Check whether both people want the same destination.',1],
['Strength','Gentle courage','Patience and emotional courage support intimacy. A calm, honest response can do more than pressure.','Insecurity may be asking for reassurance. Be kind to yourself without demanding another person fix it.',1],
['The Hermit','Room to reflect','Distance can make room for reflection. Solitude is not, by itself, proof of rejection or hidden love.','Withdrawal may have become a habit. Consider whether space is helping clarity or avoiding conversation.',0],
['Wheel of Fortune','A changing cycle','Circumstances are shifting. Be open to change while remembering that timing cannot replace mutual effort.','A repeating pattern deserves attention. Notice what you can change instead of waiting for luck.',0],
['Justice','An honest balance','Fairness asks you to weigh actions as carefully as intentions. Clear agreements help restore balance.','An uneven exchange or avoided truth needs acknowledgment. Accountability matters more than winning.',0],
['The Hanged Man','A different perspective','A pause may reveal what pursuit has hidden. You can step back without putting your whole life on hold.','Waiting without new information can become stagnation. Set a limit that protects your time.',0],
['Death','An ending and a transition','An old form of connection may be ending. Let a real change happen before asking what can begin.','Holding onto the old version of a relationship may be delaying healing. Change cannot be negotiated away.',-1],
['Temperance','Meeting halfway','Trust develops through patience and small adjustments. Balance means both people making room for each other.','Different needs or pacing may be creating strain. Seek a workable middle ground without erasing your needs.',1],
['The Devil','Attachment and intensity','Strong chemistry can coexist with an unhealthy pattern. Ask whether the bond gives you freedom as well as desire.','Recognizing a binding pattern is a chance to loosen it. Choose boundaries that return agency to you.',-1],
['The Tower','A truth breaks through','A disruption can expose what was unstable. Respond to what is actually happening rather than rebuilding an illusion.','Fear of a difficult conversation may prolong instability. A smaller honest change can be better than denial.',-1],
['The Star','Hope with room to heal','Renewed hope can return gently. Let openness grow alongside evidence of safety and reciprocal care.','Disappointment may make hope feel risky. Restore your own steadiness before seeking reassurance from the connection.',1],
['The Moon','An unclear picture','Mixed signals and uncertainty make interpretation difficult. A feeling is real, but it is not proof of another person’s intent.','Confusion may be lifting, or an assumption may need revising. Let direct evidence guide the next step.',0],
['The Sun','Openhearted clarity','Warmth and openness support a joyful connection. Look for affection that is visible, uncomplicated and mutual.','Good feelings may be present but hard to express. Lower the pressure and notice small, genuine moments.',1],
['Judgement','An honest reckoning','Reflection brings a chance to respond differently. A second chance is meaningful when someone owns what happened.','An unresolved lesson may be asking for attention. Repeating the past is different from repairing it.',0],
['The World','A cycle complete','A chapter reaches integration or closure. Appreciate what it taught you before deciding what belongs in the next one.','Something feels unfinished. Closure may come from your own understanding, even without a final conversation.',1]
];
const minors:Record<string,[string,string,string,number][]> = {
Wands:[
['A spark','New attraction or initiative has energy behind it. Let enthusiasm become a respectful first step.','A spark may be fading or blocked. Do not mistake potential for a shared plan.',1],
['Possibilities','You are considering where a connection could go. A vision becomes useful when it includes both people.','Uncertainty about the future may keep things suspended. Choose one question to clarify.',0],
['Looking ahead','An initial effort needs space to develop. Watch for a response before investing further.','Expectations may be ahead of reality. Revisit what was actually agreed.',1],
['Belonging','Shared ease and celebration can strengthen a bond. Notice whether you feel welcome as yourself.','A sense of belonging may be unsettled. Talk about what makes each of you feel at home.',1],
['Friction','Competing needs or small conflicts may be creating static. Disagreement is useful when it becomes a real conversation.','Avoiding every disagreement can hide resentment. Address one tension before it accumulates.',-1],
['Recognition','Being seen and appreciated supports confidence. Share appreciation without turning affection into a contest.','Validation may feel uneven. Public attention cannot substitute for private care.',1],
['Standing your ground','A boundary deserves a clear voice. Protect what matters without treating every difference as a threat.','Defending yourself constantly can be exhausting. Consider whether this dynamic gives you room to relax.',0],
['Swift movement','Conversation or events may gather momentum. Leave space to respond thoughtfully even when things feel exciting.','Delays or crossed messages may slow progress. Check understanding instead of assuming disinterest.',1],
['A guarded heart','Past strain may make openness difficult. Trust can grow gradually while your limits remain intact.','Exhaustion can turn caution into a wall. Decide what protection is useful and what support you need.',0],
['Too much to carry','Responsibility feels heavy. A relationship becomes difficult when one person carries its whole emotional weight.','Letting go of an unfair burden creates space. Ask for a fairer share rather than silently compensating.',-1],
['Curiosity','Playful interest invites exploration. A light, sincere gesture can reveal more than a grand declaration.','Restlessness can make interest inconsistent. Let curiosity develop before demanding certainty.',1],
['Passionate pursuit','Chemistry and initiative are strong themes. Enjoy the energy while checking for staying power.','Hot-and-cold behavior can be exciting and destabilizing. Match investment to consistency.',0],
['Confident warmth','Self-assurance makes room for generous affection. Stay connected to your own interests and friendships.','Comparison or jealousy may cloud confidence. Return attention to your own values.',1],
['A clear intention','Purposeful action can move a relationship forward. Leadership in love still requires listening.','A forceful agenda may crowd out another person’s needs. Invite input before deciding the direction.',1]],
Cups:[
['Emotional opening','A new feeling or renewed tenderness has room to emerge. Welcome it without requiring an immediate label.','Feelings may need private care before they can be shared. Refill your own emotional reserves.',1],
['Reciprocity','Mutual attention and emotional exchange support closeness. Notice how both people reach toward each other.','An imbalance or misunderstanding may interrupt connection. Repair begins with listening on both sides.',1],
['Shared joy','Friendship, community and ease can support affection. Allow a connection to exist alongside a full social life.','Social expectations may distract from the bond itself. Do not infer a third party without evidence.',1],
['Emotional distance','An offer may be overlooked while attention turns inward. Check whether withdrawal reflects your needs or a passing mood.','Interest may return after a quiet period. Be open while staying honest about what you want.',0],
['Grief and regret','Disappointment deserves acknowledgment. What was lost matters, but it need not define every possibility ahead.','Healing may be making room for a broader view. Forgiveness does not require returning.',-1],
['A familiar tenderness','Memories or familiarity can bring warmth. Compare the present relationship with the one you remember.','Nostalgia may soften the difficult parts of the past. Look at the whole history before reopening a door.',0],
['Imagined possibilities','Many possible stories can make choice difficult. Ground your attention in what has actually been said and done.','An illusion may be giving way to a clearer choice. Let concrete facts simplify the picture.',0],
['Walking toward more','Leaving an unfulfilling pattern may be necessary. Wanting more emotional depth is a valid reason to change direction.','Fear of leaving may hold you between two choices. Name what would need to change for staying to feel healthy.',-1],
['Contentment','Emotional satisfaction starts with knowing what genuinely nourishes you. Enjoy affection without making it your only source of joy.','An apparent wish fulfilled may still feel empty. Reconsider whether the goal matches your needs.',1],
['Shared emotional safety','A sense of belonging grows through mutual care. Shared happiness is built in ordinary, dependable moments.','An ideal image of love may hide unmet needs. Talk about real life rather than a perfect picture.',1],
['A tender gesture','An apology, gentle invitation or vulnerable feeling is a useful theme to explore. Give sincerity room to show itself.','A feeling may be hard to put into words. Maturity matters as much as sweetness.',1],
['Romantic expression','Affection seeks expression through words or gestures. Enjoy romance and check whether daily actions support it.','Idealization may be outrunning familiarity. Learn who someone is beyond the romantic moment.',1],
['Emotional attentiveness','Compassion and careful listening support trust. Make room for your own feelings while caring for another person.','Taking on everyone’s emotions can blur your boundaries. Kindness includes protecting your own capacity.',1],
['Emotional steadiness','Deep feeling can coexist with calm expression. Emotional maturity shows up in the way conflict is handled.','Composure may be masking avoidance. Honest vulnerability matters more than appearing untroubled.',1]],
Swords:[
['A clear conversation','A direct truth can cut through uncertainty. Choose language that is honest without being needlessly sharp.','Misunderstanding may be clouding the issue. Ask a precise question and check what you heard.',0],
['An unresolved choice','Two positions may feel hard to reconcile. A pause helps only if it makes room for information and a decision.','An avoided decision may be becoming unavoidable. Begin with the fact you have been reluctant to acknowledge.',0],
['A painful truth','Hurt or disappointment needs care and honesty. Pain is information about your experience, not a verdict on your worth.','Recovery may be possible as a painful story loosens its hold. Repair and reunion are separate choices.',-1],
['Rest before response','A quiet interval can restore perspective. Give yourself permission to stop interpreting every silence.','Restlessness may be interrupting recovery. Return to conversation only when you have enough capacity.',0],
['A costly conflict','Winning an argument may damage trust. Step away from exchanges that turn vulnerability into ammunition.','Ending a conflict takes accountability and changed conduct. Peace should not depend on one person surrendering every need.',-1],
['Moving toward calm','Distance from a difficult pattern can bring perspective. A gentler direction is possible even when transition feels sad.','An unresolved issue may travel with you. Changing the setting will not replace addressing the pattern.',0],
['Indirectness','Something may be handled indirectly or privately. Ask for clarity without assuming deception from a card.','A more honest approach may be needed. Take responsibility for your own communication and ask the same in return.',-1],
['Feeling trapped','Fear can make your options seem smaller than they are. Identify one choice that remains within your control.','A limiting story may be loosening. Try one concrete action that restores your sense of agency.',-1],
['An anxious story','Worry may be turning unknowns into worst-case scenarios. Return to observable facts and seek support outside the reading.','Relief can begin when worry is shared rather than carried alone. A thought does not have to become your prediction.',-1],
['A difficult ending','A painful chapter may have reached its limit. Give recovery priority over making the ending mean something hopeful.','Recovery takes shape after a hard ending. Reopening contact is not a requirement for healing.',-1],
['Questions and observation','Curiosity seeks information. A direct question is more respectful and useful than monitoring someone’s online activity.','Overanalysis or hasty words may create friction. Verify your interpretation before reacting.',0],
['An urgent conversation','A strong urge to speak can bring movement. Pause long enough to make your intention clear and respectful.','Impulsiveness may turn clarity into pressure. Slow the exchange and make room for a response.',0],
['Discernment','Honesty and self-respect help you see a connection clearly. A compassionate boundary can still be firm.','Protective distance may be becoming harshness. You can remain discerning without closing every door.',0],
['Clear judgment','Reasoned communication helps establish expectations. Use facts and fairness while leaving room for emotion.','Intellectual certainty may be crowding out empathy. Listening can reveal what an argument misses.',0]],
Pentacles:[
['A tangible beginning','A practical opportunity can support a connection. A small plan kept is worth more than a large promise.','An opportunity needs practical follow-through. Check whether time and capacity are actually available.',1],
['Competing priorities','Time and energy are being balanced. A workable relationship needs room in the calendar, not just good intentions.','Too many demands may make consistency difficult. Simplify expectations and be honest about capacity.',0],
['Working together','Cooperation builds trust through shared effort. Notice whether your different strengths are respected.','Uneven effort or unclear roles may create resentment. Agree on what each person can contribute.',1],
['Holding tightly','Security matters, but holding too tightly can limit openness. Ask what safety would look like without control.','Loosening a defensive grip can make room for trust. Give freely only within limits that feel sustainable.',0],
['Feeling left outside','Loneliness or lack of support may be coloring the connection. Seek care from people and places that are available.','Support may be easier to receive now. Let help in without requiring it to come from one particular person.',-1],
['A balanced exchange','Giving and receiving need room on both sides. Generosity feels safer when it is not used to create obligation.','An unequal exchange deserves a practical boundary. Affection does not create a debt.',1],
['Taking stock','Investment needs time and occasional reassessment. Ask whether effort is producing the kind of connection you want.','Impatience or poor returns may call for a change in approach. Past investment alone is not a reason to keep going.',0],
['Consistent effort','Trust grows through repeated attention to small things. Improvement is possible when both people practice it.','Routine effort may be slipping or becoming one-sided. Name the specific behavior that needs attention.',1],
['Self-possession','Independence and self-respect support freely chosen love. Enjoy a connection without abandoning a life of your own.','Approval or material reassurance may be standing in for security. Reconnect with what makes you feel capable.',1],
['Long-term foundations','Shared values and practical stability can support a future. Talk about everyday realities as well as romantic hopes.','Family expectations or long-term plans may not align. Clarify whose version of stability you are pursuing.',1],
['A small commitment','A modest, sincere offer can be a beginning. Reliability is learned through manageable steps.','Plans may remain theoretical without follow-through. Choose one achievable commitment.',1],
['Reliable progress','A slow pace can still be meaningful when actions are steady. Look for dependability rather than spectacle.','Caution may have turned into inertia. A relationship needs some observable movement as well as patience.',1],
['Practical care','Care is expressed through presence and everyday support. Make sure comfort and responsibility are shared.','Overfunctioning can leave little room for your own needs. Sustainable care includes receiving.',1],
['A dependable foundation','Consistency and practical commitment can make love feel secure. Stability works best when it includes emotional availability.','Security may be becoming possessiveness or complacency. A solid bond still needs curiosity and care.',1]]};
const ranks=['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Page','Knight','Queen','King'];
const slugify=(s:string)=>s.toLowerCase().replaceAll(' ','-');
export const cards:Card[]=[...majors.map((m,id)=>({id,slug:slugify(m[0]),name:m[0],suit:'Major Arcana',keyword:m[1],upright:m[2],reversed:m[3],tone:m[4],image:`/cards/${id}.webp`})),...Object.entries(minors).flatMap(([suit,rows],s)=>rows.map((m,i)=>{const id=22+s*14+i,name=`${ranks[i]} of ${suit}`;return{id,slug:slugify(name),name,suit,keyword:m[0],upright:m[1],reversed:m[2],tone:m[3],image:`/cards/${id}.webp`}}))];
export const questions=[
{id:'their-feelings',label:'Their feelings',title:'What are their feelings?',positions:['The emotional atmosphere','What is beneath the surface','A direction to explore'],focus:'Think about emotional availability, not only attraction.',prompt:'Look for care that shows up in consistent behavior.',count:3},
{id:'will-they-contact-me',label:'Will they contact me?',title:'Will they reach out?',positions:['The current connection','What complicates contact','Your next step'],focus:'Contact requires an actual choice; these cards cannot promise a message.',prompt:'Decide how long waiting feels healthy, and keep living your own life.',count:3},
{id:'my-ex',label:'My ex',title:'What is left between us?',positions:['The echo of the past','What remains unresolved','What supports you now'],focus:'A memory can be meaningful without being a reason to return.',prompt:'Compare the relationship you had with the one you would need now.',count:3},
{id:'reconciliation',label:'Reconciliation',title:'Could we begin again?',positions:['What could reconnect you','What would need to change','A healthier way forward'],focus:'Reconciliation needs mutual willingness and a change in the old pattern.',prompt:'Name one concrete change you would need before considering a reunion.',count:3},
{id:'our-future',label:'Our future',title:'Where is this going?',positions:['Your shared foundation','The pattern developing','What you can nurture'],focus:'A shared future is built through repeated choices, not a fixed outcome.',prompt:'Have a calm conversation about what each of you wants next.',count:3},
{id:'yes-no',label:'Yes / No',title:'A little perspective on your question',positions:['A symbolic direction'],focus:'A symbolic lean is a reflection prompt, not a factual answer.',prompt:'Use real-world evidence before making an important decision.',count:1},
{id:'three-card',label:'3 cards',title:'Where are we now?',positions:['Past — the background','Present — the situation now','Future — a possible direction'],focus:'Read these positions as perspectives on a situation, not fixed events.',prompt:'Choose one small action that is within your control.',count:3},
{id:'daily',label:'Daily tarot',title:'A moment for yourself',positions:['Today’s reflection'],focus:'Make room for one thoughtful pause today.',prompt:'Carry one useful idea into your day, then let the reading rest.',count:1}
] as const;
export type Question=(typeof questions)[number];
export type Draw={card:Card;reversed:boolean};
export function shuffled<T>(items:T[]):T[]{const a=[...items];for(let i=a.length-1;i>0;i--){const j=randomInt(i+1);[a[i],a[j]]=[a[j],a[i]]}return a}
function randomInt(n:number){const max=Math.floor(4294967296/n)*n;const b=new Uint32Array(1);do{crypto.getRandomValues(b)}while(b[0]>=max);return b[0]%n}
export function makeDeck(excluded:number[]=[]):Draw[]{return shuffled(cards.filter(c=>!excluded.includes(c.id))).map(card=>({card,reversed:randomInt(4)===0}))}
export function meaning(d:Draw){return d.reversed?d.card.reversed:d.card.upright}
export function positionMeaning(d:Draw,q:Question,index:number){const m=meaning(d);const framing:Record<string,string[]>={
 'their-feelings':['In the emotional atmosphere, this invites you to notice how closeness is expressed.','Beneath the surface, this is a theme to reflect on rather than a claim about a secret.','For the direction ahead, treat this as an invitation you can evaluate through behavior.'],
 'will-they-contact-me':['For the current connection, consider the quality of your last actual exchange.','As a complication, this asks what could make communication difficult or unclear.','For your next step, focus on what is yours to choose rather than predicting their timing.'],
 'my-ex':['In the past, this theme may help you understand what you are still carrying.','For what remains unresolved, notice whether this describes an unanswered question or a repeated pattern.','For your own wellbeing now, use this theme to choose where your attention goes.'],
 'reconciliation':['As a possible point of reconnection, this only has meaning if both people participate.','For repair, this theme highlights something to address explicitly before trying again.','For a healthier path, translate this theme into a change you could both observe.'],
 'our-future':['As a foundation, look for this theme in your everyday life together.','As a developing pattern, ask whether this is becoming more or less visible over time.','For what you can nurture, discuss this openly rather than deciding for the other person.']};return `${m} ${framing[q.id]?.[index]??q.focus}`}
export function synthesis(draws:Draw[],q:Question){const score=draws.reduce((n,d)=>n+(d.reversed?-d.card.tone:d.card.tone),0);const hasWarm=draws.some(d=>!d.reversed&&d.card.tone>0),hasTension=draws.some(d=>d.card.tone<0||d.reversed);const direction=hasWarm&&hasTension?'Warmth and hesitation appear together. The useful question is not whether one cancels out the other, but whether the connection can hold an honest conversation about both.':score>0?'The spread emphasizes openness and constructive effort. Let that possibility remain an invitation, and look for reciprocal action before increasing your investment.':score<0?'The spread emphasizes strain or limits. Give your wellbeing priority, and resist turning a difficult pattern into a challenge you must win.':'The spread leaves room for uncertainty. More reflection may help, but an observable action or a direct conversation will tell you more than another guess.';return `${draws[0].card.keyword} meets ${draws[draws.length-1].card.keyword.toLowerCase()}. ${direction} ${q.focus}`}
export const clarifiers=[
['Consistency','Notice what repeats. One warm message matters less than a pattern of thoughtful, reliable contact.'],['Timing','You can allow space without making an unlimited commitment to wait. Choose a check-in point for yourself.'],['Reciprocity','A connection should make room for both people to reach out, listen and repair. Notice who carries the effort.'],['Boundaries','A clear limit can protect tenderness. Decide what kind of communication you are comfortable receiving.'],['Assumptions','Write down what you know, then what you are imagining. They may not be the same story.'],['A conversation','Choose one honest question. Leave enough space for an answer you may not have anticipated.'],['Self-respect','You do not need to become easier to ignore in order to seem easier to love. Name your needs without apologizing for having them.'],['Space','A pause can be useful when it has a purpose. Keep your friendships, routines and plans alive during it.'],['Accountability','An apology becomes repair through changed behavior. Look for the difference between regret and responsibility.'],['Availability','A person can be appealing and still unable to offer the relationship you need. Consider capacity as well as chemistry.'],['The present','Give the current evidence more weight than a memory or an imagined future. What is happening between you now?'],['Gentleness','You can acknowledge disappointment without judging yourself for hoping. Respond at a pace that lets you stay grounded.']];
export const messages=[
'You can care deeply and still choose peace.','Let a clear action speak louder than an imagined meaning.','A connection worth keeping has room for your needs.','You do not have to solve every silence tonight.','Move at the pace of trust, not the pace of fear.','Your next chapter does not need their permission.','A gentle boundary is still a boundary.','Being chosen begins with a choice from both people.','Make room for love without putting your life on hold.','You can miss someone and still know why you left.','Let your question lead to one kind action for yourself.','What feels familiar is not always what feels safe.','You are allowed to change your mind when the facts change.','A small honest conversation can be enough for today.','Leave some room for a future you have not imagined yet.','The answer can be unfinished while your day continues.','Let reciprocity be something you observe, not something you earn.','Your attention is valuable. Choose where you place it.','Hope can walk beside discernment.','You can welcome an apology without reopening a relationship.','There is no deadline for understanding your own heart.','A steady presence can be more romantic than a grand promise.','You do not need a perfect explanation to honor your limits.','Choose the next step that lets you remain yourself.','Uncertainty is uncomfortable, but it is not an instruction to chase.','Let care be something you receive as well as give.','Today can hold something good beyond this question.','The right words matter; the next actions matter too.','You can let a feeling pass without acting on it.','Begin with the truth you already know.'];
